#### Pandas - DataFrame
- 인덱싱 , 데이터 조작 , 인덱스 조작
- loc()  - 라벨값 기반의 2차원 인덱싱 
- iloc() - 정수값 기반의 2차원 인덱싱

In [1]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib 

# titanic dataset
import seaborn as sns 



print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


In [2]:
def seriesInfo(s) :
    print('series : index + values \n' , s) 
    print('index  - ' , s.index  , type(s.index))
    print('values - ' , s.values , type(s.values))

def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

- 개별인덱싱

In [3]:
score_data = {
    'kor'  : [80, 90, 70, 30] , 
    'eng'  : [90, 70, 60, 40] , 
    'math' : [90, 60, 90, 70] , 
}

col_idx = ['kor' , 'eng' , 'math']
row_idx = ['박현상' , '이지희' , '최재우' , '손현진']

tmp_frm = pd.DataFrame(score_data , columns = col_idx , index = row_idx)
frmInfo(tmp_frm)

'data - '

kor  eng  math
박현상   80   90    90
이지희   90   70    60
최재우   70   60    90
손현진   30   40    70


shape   -  (4, 3) 4 3
size    -  12
ndim    -  2
index   -  Index(['박현상', '이지희', '최재우', '손현진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


In [4]:
print( tmp_frm['kor'] , type(tmp_frm['kor']) )

박현상    80
이지희    90
최재우    70
손현진    30
Name: kor, dtype: int64 <class 'pandas.core.series.Series'>


In [5]:
print('모든 학생의 영어 점수와 국어점수만 조회한다면? ')
print()
frmInfo( tmp_frm[ ['kor' , 'eng'] ]  )


모든 학생의 영어 점수와 국어점수만 조회한다면? 



'data - '

kor  eng
박현상   80   90
이지희   90   70
최재우   70   60
손현진   30   40


shape   -  (4, 2) 4 2
size    -  8
ndim    -  2
index   -  Index(['박현상', '이지희', '최재우', '손현진'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90]
 [90 70]
 [70 60]
 [30 40]] <class 'numpy.ndarray'>


In [6]:
print('모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - ')
print()

모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - 



In [7]:
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

kor  eng  math        avg
박현상   80   90    90  86.666667
이지희   90   70    60  73.333333
최재우   70   60    90  73.333333
손현진   30   40    70  46.666667

In [8]:
print('손현진 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? ')
print()
tmp_frm['eng']['손현진'] = 90
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

손현진 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? 



kor  eng  math        avg
박현상   80   90    90  86.666667
이지희   90   70    60  73.333333
최재우   70   60    90  73.333333
손현진   30   90    70  59.166667

In [9]:
print( tmp_frm[ :'박현상'] , type(tmp_frm[ :'박현상']) )


     kor  eng  math        avg
박현상   80   90    90  86.666667 <class 'pandas.core.frame.DataFrame'>


In [10]:
print( tmp_frm.T['박현상'] , type(tmp_frm.T['박현상']) )

kor     80.000000
eng     90.000000
math    90.000000
avg     86.666667
Name: 박현상, dtype: float64 <class 'pandas.core.series.Series'>


In [11]:
sample_frm = pd.DataFrame( np.arange(10, 22).reshape(3,4) , 
                           index = ['a', 'b', 'c'] , 
                           columns = ['col01' , 'col02', 'col03' , 'col04'])
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

In [12]:
seriesInfo( sample_frm.loc['a'] )


series : index + values 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32
index  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [10 11 12 13] <class 'numpy.ndarray'>


In [13]:
print('loc[행 인덱스 값 , 열 인덱스 값]')

sample_frm.loc['a'].values

loc[행 인덱스 값 , 열 인덱스 값]


array([10, 11, 12, 13])

In [14]:
sample_frm.iloc[0]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32

In [15]:
sample_frm.loc[ ['a','c'] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [16]:
sample_frm.iloc[ [0 , 2] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [17]:
sample_frm.loc[ 'b' : 'c']

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [18]:
sample_frm[ 'b' : 'c' ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [19]:
sample_frm.loc[ ['b' , 'c'] ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [20]:
sample_frm['col01'] > 15

a    False
b    False
c     True
Name: col01, dtype: bool

In [21]:
sample_frm.loc[ sample_frm['col01'] > 15 ] 

col01  col02  col03  col04
c     18     19     20     21

In [22]:
sample_frm.loc[ 'a' , 'col01' ]

10

In [23]:
sample_frm.loc[ 'a' : 'b' , 'col01' ]

a    10
b    14
Name: col01, dtype: int32

In [24]:
sample_frm.loc[ 'a'  , : ]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int32

In [25]:
sample_frm.loc[ 'a'  , ['col03' , 'col04'] ]

col03    12
col04    13
Name: a, dtype: int32

In [26]:
sample_frm.iloc[ :  , -2 : ]

col03  col04
a     12     13
b     16     17
c     20     21

In [27]:
sample_frm.iloc[-1] = sample_frm.iloc[-1] * 2 
sample_frm


col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42

In [28]:
sample_frm.loc['d'] = 0
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0

In [29]:
sample_frm.loc['e'] = sample_frm.loc['d']
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     36     38     40     42
d      0      0      0      0
e      0      0      0      0

In [30]:
print('새로운 열 추가 - ')
sample_frm['col05'] = sample_frm['col04']
sample_frm

새로운 열 추가 - 


col01  col02  col03  col04  col05
a     10     11     12     13     13
b     14     15     16     17     17
c     36     38     40     42     42
d      0      0      0      0      0
e      0      0      0      0      0

In [31]:
sample_frm.iloc[1 , 1]

15

- 데이터프레임 조작 , count()

In [32]:
tmp_series = pd.Series( range(10) ) 
tmp_series[5] = np.NaN
tmp_series.count()

9

In [33]:
cnt_frm = pd.DataFrame( np.random.randint(5, size=(4,4)) , 
                        columns = ['col01' , 'col02', 'col03' , 'col04'] )

cnt_frm

col01  col02  col03  col04
0      0      2      0      3
1      4      4      1      3
2      4      1      2      4
3      0      4      4      3

In [34]:
cnt_frm.iloc[1 , 0] = np.NaN
cnt_frm.iloc[3 , 0] = np.NaN
cnt_frm.iloc[2 , 3] = np.NaN

In [35]:
cnt_frm.count()

col01    2
col02    4
col03    4
col04    3
dtype: int64

#### 타이타닉 데이터를 활용한 프레임 [실습]

In [36]:
datasets = sns.load_dataset('titanic')
print('type - ' , type(datasets))

type -  <class 'pandas.core.frame.DataFrame'>


In [37]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [38]:
datasets.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [39]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [40]:
datasets.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [41]:
datasets.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [42]:
datasets['class'].value_counts().values

array([491, 216, 184], dtype=int64)

In [43]:
datasets['new_col'] = 0
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  new_col  
0    man        True  NaN  Southampton    no  False        0  
1  woman       False    C    Cherbourg   yes  False        0  
2  woman       False  NaN  Southampton   yes   True        0  
3  woman       False    C  Southampton   yes  False        0  
4    man        True  NaN  Southampton    no   True        0

In [44]:
del datasets['new_col']
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [45]:
print('age_by_10 컬럼을 추가하고자 한다 - ') 
print('age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다면? - ')
print()

datasets['age_by_10'] = datasets['age'] + 10
datasets.head()


age_by_10 컬럼을 추가하고자 한다 - 
age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다면? - 



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False       32.0  
1  woman       False    C    Cherbourg   yes  False       48.0  
2  woman       False  NaN  Southampton   yes   True       36.0  
3  woman       False    C  Southampton   yes  False       45.0  
4    man        True  NaN  Southampton    no   True       45.0

In [46]:
datasets['parch'].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: parch, dtype: int64

In [47]:
print('parch 와 sibsp의 값과 1을 더한 family_no 컬럼 생성한다면? - ')
print()

datasets['family_no'] = datasets['parch'] + datasets['sibsp'] + 1
datasets.head()

parch 와 sibsp의 값과 1을 더한 family_no 컬럼 생성한다면? - 



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

- 다중 컬럼을 삭제한다면? 
- drop(label = ,  axis = 1(열) | 0(행) , inplace = T|F )

In [48]:
print('새롭게 만든 2개의 컬럼을 삭제한다면? drop() 이용 - ')
print()

datasets.drop(['age_by_10' , 'family_no'] , axis = 1 , inplace = True)
datasets

새롭게 만든 2개의 컬럼을 삭제한다면? drop() 이용 - 



survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [49]:
# datasets.drop( [0, 1, 2 ] , axis = 0 , inplace = True)
datasets

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [50]:
type( datasets.index.values )

numpy.ndarray

In [51]:
datasets.index.values[ : 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [52]:
type( datasets.columns.values )

numpy.ndarray

In [53]:
datasets.columns.values[: 10 ]

array(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who'], dtype=object)

In [54]:
fare_series = datasets['fare']
print('type - ' , type(fare_series))
print()

print('data - ' , fare_series.values , type( fare_series.values ))
print()

print('max - ' , np.max(fare_series))
print('min - ' , fare_series.min())
print('sum - ' , fare_series.sum())

type -  <class 'pandas.core.series.Series'>

data -  [  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7

In [55]:
datasets.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

- 인덱스를 재 정의하는 방법
- reset_index() : 새로운 인덱스 할당, 기존 인덱스를 열로 추가할 수 있다.
- set_index()

In [56]:
datasets

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [57]:
titanic_dataset = pd.read_csv('./pandas_data/titanic_train.csv')
titanic_dataset.head()

FileNotFoundError: [Errno 2] No such file or directory: './pandas_data/titanic_train.csv'

In [ ]:
titanic_dataset_set_index = titanic_dataset.set_index('PassengerId')
titanic_dataset_set_index

In [ ]:
titanic_dataset_reset_index = titanic_dataset.reset_index(inplace = False)
titanic_dataset_reset_index

In [ ]:
titanic_dataset

In [ ]:
print('Pclass 가 3 등급인 데이터만 확인 - ') 
boolean_idx = titanic_dataset['Pclass'] == 3 
boolean_idx

# titanic_dataset[boolean_idx][['Sex', 'Age']]
titanic_dataset[boolean_idx].iloc[ : , [4, 5]]

In [ ]:
print('나이가 60 이상인 정보만 출력한다면 - ')
print('Pclass , Survived, Name - loc[] ')
print()

# titanic_dataset['Age'] >= 60 
# titanic_dataset[ titanic_dataset['Age'] >= 60 ] [['Pclass', 'Survived', 'Name']]
titanic_subset = titanic_dataset.loc[ titanic_dataset['Age'] >= 60  , ['Pclass', 'Survived', 'Name']]
titanic_subset.reset_index(inplace=True)
titanic_subset.drop('index' , axis = 1 , inplace = True)
titanic_subset

In [ ]:
print('승객의 평균나이를 계산한다면 - ' , titanic_dataset['Age'].mean() )
print('승객의 평균나이를 계산한다면 - ' , titanic_dataset.loc[ : , 'Age'].mean())
print()


print('여성승객의 평균나이를 계산한다면 - ' , titanic_dataset['Age'][titanic_dataset['Sex'] == 'female'].mean()) 
print('여성승객의 평균나이를 계산한다면 - ' , titanic_dataset.loc[ titanic_dataset['Sex'] == 'female' , 'Age'].mean() ) 
print()

In [ ]:
print('1등급 선실의 여성승객의 평균나이를 계산한다면 - ') 
print( titanic_dataset[titanic_dataset['Pclass'] == 1][titanic_dataset['Sex'] == 'female']['Age'].mean() )

print( titanic_dataset.loc[(titanic_dataset['Pclass'] == 1) & (titanic_dataset['Sex'] == 'female'), 'Age'].mean() )


- 정렬
- sort_index
- soert_values

In [ ]:
series_value = pd.Series( np.random.randint(6, size=100))
series_value

In [ ]:
series_value.value_counts()

In [ ]:
series_value.value_counts().sort_index()

In [ ]:
series_value.value_counts().sort_values()

In [ ]:
series_value.value_counts().sort_values(ascending = False )

In [ ]:
sort_frm = pd.DataFrame( np.random.randint(0, 10 , (6,4)))
sort_frm

In [ ]:
sort_frm.index = pd.date_range('20220328' , periods = 6)
sort_frm.columns = ['A', 'B', 'C', 'D' ]
sort_frm

In [ ]:
random_date = np.random.permutation(sort_frm.index)
# random_date

r_sort_frm = sort_frm.reindex( index   = random_date , 
                               columns = ['B', 'A', 'D', 'C'])
r_sort_frm

In [ ]:
print('프레임에 정렬을 할 경우 by - 정렬 기준이되는 열을 지정')
# sort_frm.sort_values(by='B')
sort_frm.sort_values(by='B')

In [ ]:
sort_frm

In [ ]:
print('sort_index(axis =  , ascending = ) - ') 
# r_sort_frm.sort_index( axis = 1 , ascending = False ) 
r_sort_frm.sort_index( axis = 0 , ascending = True ) 

In [ ]:
print('sort_values(by = , ascending = ) - ')
print('열의 값을 기준으로 행 정렬 - ') 
r_sort_frm.sort_values(by=['B', 'A'] , ascending = False ) 

In [ ]:
print('승객의 나이를 기준으로 내림차순 정렬한다면 - ')
titanic_dataset.sort_values('Age', ascending = False)


In [ ]:
print('sort_values - ')
print('승객의 성별   인원수를 정렬하라 - ')
print( titanic_dataset['Sex'].value_counts().sort_values(ascending = False))
print()

print('승객의 나이별 인원수를 정렬하라 - ')
print(titanic_dataset['Age'].value_counts().sort_values(ascending = False))
print()

print('승객의 선실별 인원수를 정렬하라 - ')
print(titanic_dataset['Pclass'].value_counts().sort_values(ascending = False))
print()

print('승객의 사망/생존별 인원수를 정렬하라 - ')
print(titanic_dataset['Survived'].value_counts().sort_values(ascending = False))
print()


- rank()

In [ ]:
print('승객의 나이를 기준으로 내림차순 정렬하고 순위를 부여한다면? - ') 
subset = titanic_dataset.sort_values(by = 'Age' , ascending = False )
rank = subset['Age'].rank(ascending = False)
subset['rank'] = rank 
subset

- year2020_baby_name.csv 파일로드 및 데이터구조 확인하기

In [ ]:
datasets = pd.read_csv('./pandas_data/year2020_baby_name.csv' , sep=',' , encoding='utf-8' )
print('type - ' , type(datasets))
datasets.info()

In [ ]:
print('count 내려차순 정렬을 한다면? - ')
name_subset = datasets.sort_values(by='COUNT' , ascending = False )
name_subset

In [ ]:
print('인덱스 재 조정 - ')
name_subset.reset_index(inplace = True)
name_subset

In [ ]:
name_subset.drop('index' , axis = 1 , inplace = True )
name_subset

In [ ]:
print('순위 만들어서 새로운 컬럼으로 추가 - ') 
rank_series = name_subset['COUNT'].rank(ascending = False )
name_subset['rank'] = rank_series
name_subset.info()

In [ ]:
name_subset['rank'].astype('int64')
name_subset.info()

In [ ]:
print('성별이 여자인 데이터만 서브셋을 만든다면? -  ')
f_gender_frm = name_subset[ name_subset['GENDER'] == 'F']
print()
print()
print('성별이 남자인 데이터만 서브셋을 만든다면? -  ')
m_gender_frm = name_subset[ name_subset['GENDER'] == 'M']
print()
print()


In [ ]:
f_gender_frm

In [ ]:
m_gender_frm